name: "Deploy CineWave"
on:
  push:
    branches:
      - main
    tags:
      - "CineWave/v*"

env:
  PROJECT_PATH: "CineWave/CineWave.csproj"

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0"

      - name: Restore NuGet packages
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build the project
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

      - name: Publish the project
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true --no-build

      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - uses: csexton/release-asset-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pattern: "CineWave/bin/Release/net7.0/win-x64/publish/*.exe"
          release-url: ${{ steps.create_release.outputs.upload_url }}